### ISSUE TITLE
Pay it forward

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Home#1]
* https://github.com/xunit/xunit/issues/1860
 * https://github.com/jbevain/cecil/issues/552
 * https://github.com/approvals/ApprovalTests.Net/issues/251
 * https://dependabot.com/#pricing

**Comment by sawilde** [comment]
@SimonCropp I'd be interested on how that model goes. 

I used to have a gift button on OpenCover to try to help cover hosting of the build pipeline but now all the tooling is free other than time OpenCover costs me nothing financially. I'm more of a my contribution is like a time bank and so I can use other people's contributions to the OS world.

**Comment by tonyqus** [comment]
I'm reading your pay-forward model. This is also something I'm looking into recently. I'm thinking how to distribute donation via web3 protocol such as TON network so that anyone in the open source supply chain can get profits 

However, I also see a few project maintainers declined your payment perhaps they don't need donation? I don't know.
